<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>WindowsApp.Net6</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
    <StartupObject>WindowsApp.Program</StartupObject>
    <TargetFramework>net6.0-windows</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Net6\Net6.Windows\Net6.Windows.csproj" />
  </ItemGroup>

</Project>
